### PR TITLE
Clean up update printing, don't fetch on new sessions when cloning, bug fix

### PR DESCRIPTION
**Pull request by ShaneSmiskol**
- Create a file at `/data/community/.oh-my-comma/.cloning` that .bashrc checks to not fetch if emu utils is cloning/setting up in another session. It would previously start cloning in the new session without a way to exit
- Clean up update printing so it's shorter and cleaner.
- Catch an exception when user enters branch for `fork switch` without the `-b` flag
- Catch KeyboardInterrupt exception while cloning

TODO:
- [x] it won't update the `.bashrc` if it's changed since the last update, not sure how to fix that

### CODE REVIEW

**Comment by ShaneSmiskol** [comment]
@AskAlice Is there any drawback to deleting `/data/community/.bashrc` on update? The script copies it back with the latest version

**Comment by AskAlice** [comment]
Yes. It's the only entry point users have to shell init without overwriting system. The .bashrc is a place for us to put some starter additions, and let the users add whatever else they're used to in their Unix shell environment. It's simply an entry point for `emu.sh`, though honestly at this point it makes more sense for emu to be a binary.

My point is its a shared space. Let's not step on other users feet

**Comment by ShaneSmiskol** [comment]
Well as it stands now, it won't overwrite or delete the current file. I can make a message in the update to remind users that new additions might have been added and a command to reset it on updates when it's changed

**Comment by ShaneSmiskol** [comment]
This is what the update screen looks like now btw

Screenshot_116

**Pull request merged**
